# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SimPlus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SimPlus.proto',
  package='Simplus',
  syntax='proto3',
  serialized_options=_b('\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\rSimPlus.proto\x12\x07Simplus\";\n\nWorldModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\"C\n\x0cRobotCommand\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\n\n\x02vx\x18\x02 \x01(\x01\x12\n\n\x02vy\x18\x03 \x01(\x01\x12\n\n\x02vw\x18\x04 \x01(\x01\x32\x42\n\x04Play\x12:\n\nGetCommand\x12\x13.Simplus.WorldModel\x1a\x15.Simplus.RobotCommand\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_WORLDMODEL = _descriptor.Descriptor(
  name='WorldModel',
  full_name='Simplus.WorldModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Simplus.WorldModel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='Simplus.WorldModel.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Simplus.WorldModel.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Simplus.WorldModel.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=85,
)


_ROBOTCOMMAND = _descriptor.Descriptor(
  name='RobotCommand',
  full_name='Simplus.RobotCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='Simplus.RobotCommand.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vx', full_name='Simplus.RobotCommand.vx', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vy', full_name='Simplus.RobotCommand.vy', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vw', full_name='Simplus.RobotCommand.vw', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['WorldModel'] = _WORLDMODEL
DESCRIPTOR.message_types_by_name['RobotCommand'] = _ROBOTCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WorldModel = _reflection.GeneratedProtocolMessageType('WorldModel', (_message.Message,), {
  'DESCRIPTOR' : _WORLDMODEL,
  '__module__' : 'SimPlus_pb2'
  # @@protoc_insertion_point(class_scope:Simplus.WorldModel)
  })
_sym_db.RegisterMessage(WorldModel)

RobotCommand = _reflection.GeneratedProtocolMessageType('RobotCommand', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCOMMAND,
  '__module__' : 'SimPlus_pb2'
  # @@protoc_insertion_point(class_scope:Simplus.RobotCommand)
  })
_sym_db.RegisterMessage(RobotCommand)


DESCRIPTOR._options = None

_PLAY = _descriptor.ServiceDescriptor(
  name='Play',
  full_name='Simplus.Play',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=222,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCommand',
    full_name='Simplus.Play.GetCommand',
    index=0,
    containing_service=None,
    input_type=_WORLDMODEL,
    output_type=_ROBOTCOMMAND,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLAY)

DESCRIPTOR.services_by_name['Play'] = _PLAY

# @@protoc_insertion_point(module_scope)
