# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import SimPlus_pb2 as SimPlus__pb2


class PlayStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetCommand = channel.unary_unary(
        '/Simplus.Play/GetCommand',
        request_serializer=SimPlus__pb2.WorldModel.SerializeToString,
        response_deserializer=SimPlus__pb2.RobotCommand.FromString,
        )


class PlayServicer(object):
  """The greeting service definition.
  """

  def GetCommand(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PlayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetCommand': grpc.unary_unary_rpc_method_handler(
          servicer.GetCommand,
          request_deserializer=SimPlus__pb2.WorldModel.FromString,
          response_serializer=SimPlus__pb2.RobotCommand.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Simplus.Play', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
